import React, { useState } from 'react';
import Nav from './Nav';
import Head from 'next/head';
import { Box, Flex, HStack, Text, useColorMode, useColorModeValue } from '@chakra-ui/react';

export default function Layout({ children })
{
    const { toggleColorMode } = useColorMode();
    const [ isDarkMode, setIsDarkMode] = useState(false);

    const bgColor = useColorModeValue('white', 'gray.500');

    return (
        <>
            <Head>
                <title>Piegon Koop Cabin</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Flex flexDir='column' bg={bgColor} h='100vh' alignItems='stretch' w='100vw' overflowX='hidden' pb='40px'>
                <Nav toggleColor={toggleColorMode} isDarkMode={isDarkMode} setIsDarkMode={setIsDarkMode} />
                <Box h='100%'>
                    { children }
                </Box>
                <HStack h='40px' bg='gray.700' w='100%' justifyContent='center' alignItems='center' position='absolute' bottom='0' zIndex='1000'>
                    <Text color='white' fontWeight='bold'>Notice a problem? Deal with it</Text>
                </HStack>
            </Flex>
        </>
       
    )
}